"""add_graduation_and_linkedin_fields

Revision ID: 4371abd2b500
Revises: 415d72f19af6
Create Date: 2026-07-25 04:49:01.908217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4371abd2b500'
down_revision = '415d72f19af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nota: "ix_documents_entity" no lo crea ninguna migración anterior (fue
    # autogenerado contra una base local que lo tenía por otra vía). Se usa
    # IF EXISTS para que la migración funcione en cualquier base, la tenga o no.
    op.execute("DROP INDEX IF EXISTS ix_documents_entity")
    op.add_column('students', sa.Column('is_graduation_project', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('students', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('tutors', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'linkedin_url')
    op.drop_column('students', 'linkedin_url')
    op.drop_column('students', 'is_graduation_project')
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_documents_entity ON documents (entity_type, entity_id)"
    )
    # ### end Alembic commands ###
