"""add_graduation_and_linkedin_fields

Revision ID: 4371abd2b500
Revises: 415d72f19af6
Create Date: 2026-07-25 04:49:01.908217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4371abd2b500'
down_revision = '415d72f19af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_entity'), table_name='documents')
    op.add_column('students', sa.Column('is_graduation_project', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('students', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('tutors', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'linkedin_url')
    op.drop_column('students', 'linkedin_url')
    op.drop_column('students', 'is_graduation_project')
    op.create_index(op.f('ix_documents_entity'), 'documents', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
