"""add status and summary to meetings

Revision ID: 879259fc00ab
Revises: 4371abd2b500
Create Date: 2026-07-27 20:33:55.561882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879259fc00ab'
down_revision = '4371abd2b500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('status', sa.Enum('SCHEDULED', 'HELD', 'CANCELLED', name='meeting_status', native_enum=False, length=20), server_default='Scheduled', nullable=False))
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'summary')
    op.drop_column('meetings', 'status')
    # ### end Alembic commands ###
