"""add checkpoints

Revision ID: c8201599226e
Revises: 4371abd2b500
Create Date: 2026-07-27 20:12:51.787812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8201599226e'
down_revision = '4371abd2b500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='checkpoint_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoint_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('respondent_type', sa.Enum('TUTOR', 'STUDENT', name='respondent_type'), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('attendance_ok', sa.Boolean(), nullable=True),
    sa.Column('progress_ok', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoint_responses')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
